version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # - echo $AWS_DEFAULT_REGION
      - echo us-east-1
      # - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 648526511106.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd app
      - ls -lrt
      # - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      # - docker build -t node-js:v1 .
      # # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # - docker tag node-js:v1 648526511106.dkr.ecr.us-east-1.amazonaws.com/node-js:latest
  post_build:
    commands:
      - echo Build completed on `date`
      # - echo Pushing the Docker image...
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # - docker push 648526511106.dkr.ecr.us-east-1.amazonaws.com/node-js:latest
